#!/usr/bin/env node
// Plan 01 Q2 — Certificate Transparency monitoring.
//   node --env-file=.env cert-watch.mjs [--company=lovable] [--dry-run]
//
// For each competitor domain, queries crt.sh for every TLS cert ever issued
// for a subdomain of that domain. Compares against the previous snapshot;
// any new subdomain = signal.
//
// Why this is a leading indicator: companies provision TLS certs 2–8 weeks
// BEFORE publicly announcing what's on the subdomain. A cert for
// `healthcare.<vendor>.ai` appearing in CT logs today → "<vendor> launches
// healthcare vertical" press release 4–8 weeks later.
//
// Sources:
//   - crt.sh free JSON API, no auth, no rate limit worth mentioning
//   - https://crt.sh/?q=%25.lovable.ai&output=json returns every cert

import { COMPANIES } from './companies.mjs';
import { impactBand } from './scoring.mjs';
import {
  appendSignal, alreadySeen,
  loadCertSnapshot, saveCertSnapshot,
} from './store.mjs';
import { notifySignal, getToastStats } from './notify.mjs';

const USER_AGENT = 'Signal-CertWatch/0.1 (+https://gledach.de)';
const TIMEOUT_MS = 30_000;
const INTER_COMPANY_DELAY_MS = 1500;
const MAX_NEW_SIGNALS_PER_COMPANY = 20;
const RETRY_COUNT = 2;

// ─── arg parsing ───────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const COMPANY_FILTER = argv.find((a) => a.startsWith('--company='))?.split('=')[1];
const DRY_RUN = argv.includes('--dry-run');

// ─── subdomain keyword scoring ─────────────────────────────────────────────
// Subdomains matching these patterns get a score boost.
// FIRST-LABEL patterns anchor at the leftmost subdomain label.
// WHOLE-LABEL patterns match anywhere in the leftmost label (catches
// customer-named deal subdomains like "aetna-msa-proposal").
const HOT_KEYWORDS = [
  // First-label anchors — strategic categories
  { pattern: /^enterprise|^biz\b/i, label: 'enterprise-push', boost: 25 },
  { pattern: /^(healthcare|health|medical|clinical|hospital|hipaa|pharma)\b/i, label: 'healthcare', boost: 30 },
  { pattern: /^(finance|banking|fintech|lending|wealth|bank)\b/i, label: 'finance', boost: 25 },
  { pattern: /^(insurance|underwrit|claim)\b/i, label: 'insurance', boost: 25 },
  { pattern: /^(realtor|realestate|real-estate|mortgage|property)\b/i, label: 'realestate', boost: 25 },
  { pattern: /^(retail|ecommerce|shopify|merchant|commerce)\b/i, label: 'retail', boost: 20 },
  { pattern: /^(telecom|telco|carrier|mvno)\b/i, label: 'telecom', boost: 25 },
  { pattern: /^(bpo|contact[-_]?center|call[-_]?center)\b/i, label: 'bpo', boost: 25 },
  { pattern: /^(eu|europe|emea|uk|de|fr|nl|es|it)\b/i, label: 'geo-eu', boost: 20 },
  { pattern: /^(apac|asia|japan|jp|india|in|singapore|sg|korea|kr|china|cn)\b/i, label: 'geo-apac', boost: 25 },
  { pattern: /^(latam|brazil|br|mexico|mx|argentina|ar)\b/i, label: 'geo-latam', boost: 20 },
  { pattern: /^(partners?|integrations?|marketplace)\b/i, label: 'partnership', boost: 20 },
  { pattern: /^(api[-_]?v[0-9]|v[0-9])\b/i, label: 'api-version', boost: 20 },
  { pattern: /^(launch|announce|beta|preview)\b/i, label: 'launch', boost: 15 },
  { pattern: /^(voice|audio|realtime|phone|call)\b/i, label: 'voice-product', boost: 15 },
  { pattern: /^(agent|agents|bot|assistant)\b/i, label: 'agent-product', boost: 10 },
  { pattern: /^(ai|ml)\b/i, label: 'ai-product', boost: 5 },

  // Whole-label patterns — customer-deal-stage + integration-partner + compliance markers
  { pattern: /(^|[-_])msa([-_]|$)/i, label: 'customer-MSA', boost: 25 },
  { pattern: /(^|[-_])(pilot|poc|trial|eval|evaluation)([-_]|$)/i, label: 'customer-pilot', boost: 20 },
  { pattern: /(^|[-_])(proposal|quote|rfp)([-_]|$)/i, label: 'customer-proposal', boost: 20 },
  { pattern: /(^|[-_])(demo|showcase)([-_]|$)/i, label: 'customer-demo', boost: 10 },
  { pattern: /^(trust|compliance|security|privacy|soc2|iso27001)\b/i, label: 'compliance', boost: 20 },
  { pattern: /^(status|uptime|health)\b/i, label: 'status-page', boost: 5 },
  { pattern: /^(mcp|mcps|anthropic|claude)\b/i, label: 'mcp-integration', boost: 20 },
  { pattern: /^(openai|gpt|chatgpt|realtime)\b/i, label: 'openai-integration', boost: 15 },
  { pattern: /^(hubspot|salesforce|zendesk|intercom|slack|vercel|netlify|supabase|stripe|zapier|segment|snowflake)\b/i, label: 'integration-partner', boost: 15 },
];

// These are probably CDN-autogenerated, internal staging, or obvious noise.
const SKIP_PATTERNS = [
  /^(www|mail|smtp|imap|pop|mx\d*|ns\d*|dns\d*|ftp|sftp)\./i,
  /^(autodiscover|autoconfig|_domainkey|_dmarc|_acme-challenge)\./i,
  /^(staging|dev|test|qa|ci|preview|uat|sandbox|local)\b/i,
  /^[a-f0-9-]{20,}\./i,                             // long hex strings = auto-generated
  /^[a-z0-9]+-[a-z0-9]{8,}-[a-z0-9]+\./i,           // "foo-a1b2c3d4-us-east" cdn style
  /\.(pages|workers|vercel|netlify|herokuapp|appspot)\.dev$/i,  // PaaS wildcard artifacts
];

// ─── main ──────────────────────────────────────────────────────────────────
async function main() {
  const targets = COMPANY_FILTER
    ? [COMPANIES[COMPANY_FILTER]].filter(Boolean)
    : Object.values(COMPANIES);

  console.log(`[cert-watch] ${targets.length} targets${DRY_RUN ? ' [DRY-RUN]' : ''}`);

  let totalNew = 0;
  let totalSkipped = 0;

  for (const company of targets) {
    console.log(`\n── ${company.name} (${company.domain}) ──`);

    let allSubdomains;
    try {
      allSubdomains = await fetchCTLogs(company.domain);
    } catch (err) {
      console.warn(`  FAIL: ${err?.message || err}`);
      await sleep(INTER_COMPANY_DELAY_MS);
      continue;
    }

    const { kept, skipped } = filterSubdomains(allSubdomains);
    totalSkipped += skipped;
    console.log(`  ${allSubdomains.size} total · ${kept.length} after skip-filter · ${skipped} skipped`);

    const { newCount, skippedCount } = await handleSubdomainDiff(company, kept);
    totalNew += newCount;

    await sleep(INTER_COMPANY_DELAY_MS);
  }

  const toasts = getToastStats();
  console.log(`\n[cert-watch] done — newSubdomains=${totalNew} skipped=${totalSkipped} toasts=${toasts.count}/${toasts.max}`);
}

// ─── fetch + parse crt.sh ──────────────────────────────────────────────────
async function fetchCTLogs(domain) {
  // crt.sh sometimes returns 504/502 under load — retry with backoff.
  const url = `https://crt.sh/?q=%25.${encodeURIComponent(domain)}&output=json`;
  let lastErr;
  for (let attempt = 0; attempt <= RETRY_COUNT; attempt++) {
    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
      const res = await fetch(url, {
        headers: { 'user-agent': USER_AGENT, accept: 'application/json' },
        signal: ctrl.signal,
      }).finally(() => clearTimeout(t));
      if (res.status === 502 || res.status === 504) {
        lastErr = new Error(`HTTP ${res.status} (transient)`);
        if (attempt < RETRY_COUNT) { await sleep(2000 * (attempt + 1)); continue; }
        throw lastErr;
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (!Array.isArray(data)) throw new Error('crt.sh returned non-array');
      return flattenNameValues(data, domain);
    } catch (err) {
      lastErr = err;
      if (attempt < RETRY_COUNT) { await sleep(2000 * (attempt + 1)); continue; }
      throw err;
    }
  }
  throw lastErr;
}

function flattenNameValues(certArray, rootDomain) {
  // Each cert has a `name_value` that can be multi-line with several SANs.
  // Collect every unique lowercased host matching *.rootDomain.
  const out = new Set();
  const root = rootDomain.toLowerCase();
  for (const c of certArray) {
    const nv = c?.name_value;
    if (!nv || typeof nv !== 'string') continue;
    for (const raw of nv.split('\n')) {
      const host = raw.trim().toLowerCase();
      if (!host) continue;
      if (host.includes('@')) continue; // email SANs
      // Must end in .rootDomain OR equal rootDomain; skip root itself.
      if (host === root) continue;
      if (!host.endsWith(`.${root}`)) continue;
      out.add(host);
    }
  }
  return out;
}

// ─── filter noise ──────────────────────────────────────────────────────────
function filterSubdomains(all) {
  const kept = [];
  let skipped = 0;
  for (const host of all) {
    // Strip wildcard prefix for SKIP-pattern matching but keep the host as-is in the set.
    const normalized = host.replace(/^\*\./, '');
    if (SKIP_PATTERNS.some((re) => re.test(normalized))) {
      skipped++;
      continue;
    }
    kept.push(host);
  }
  return { kept: kept.sort(), skipped };
}

// ─── scoring ───────────────────────────────────────────────────────────────
function scoreSubdomain(host) {
  // Patterns match against the leftmost label (e.g., "healthcare" in
  // "healthcare.lovable.ai", or "aetna-msa-proposal" in
  // "aetna-msa-proposal.retellai.com"). Whole-label patterns can match
  // any position within that first label; first-anchored patterns are ^-anchored.
  const normalized = host.replace(/^\*\./, '');
  const firstLabel = normalized.split('.')[0] || '';
  const matches = [];
  let boost = 0;
  for (const { pattern, label, boost: b } of HOT_KEYWORDS) {
    if (pattern.test(firstLabel)) {
      if (!matches.includes(label)) {
        matches.push(label);
        boost += b;
      }
    }
  }
  // Wildcard-only certs are lower-signal (might be defensive, not a new product).
  const isWildcard = host.startsWith('*.');
  const base = isWildcard ? 35 : 50;
  const score = Math.min(95, base + Math.min(boost, 45));
  return { score, matches, isWildcard };
}

// ─── diff + emit ───────────────────────────────────────────────────────────
async function handleSubdomainDiff(company, currentList) {
  const prior = await loadCertSnapshot(company.id);
  const prevList = Array.isArray(prior?.subdomains) ? prior.subdomains : null;
  const prevSet = new Set(prevList || []);
  const currentSet = new Set(currentList);

  const added = currentList.filter((h) => !prevSet.has(h));
  const removed = (prevList || []).filter((h) => !currentSet.has(h));

  const firstRun = prevList === null;
  if (firstRun) {
    console.log(`  first run — baseline saved (${currentList.length} subdomains), no signals emitted`);
  } else {
    console.log(`  diff: +${added.length} new, -${removed.length} removed (removed are informational only)`);

    let emitted = 0;
    let skippedDup = 0;
    for (const host of added) {
      if (emitted >= MAX_NEW_SIGNALS_PER_COMPANY) break;
      const { score, matches, isWildcard } = scoreSubdomain(host);
      const hashId = `cert:new-subdomain:${company.id}:${host}`;

      if (!DRY_RUN && (await alreadySeen(hashId))) {
        skippedDup++;
        continue;
      }

      const reasonLabel = matches.length ? matches.join(', ') : 'no keyword match';
      const summary = `Certificate for ${host} appeared in crt.sh logs. Boost reasons: ${reasonLabel}${isWildcard ? ' (wildcard)' : ''}.`;
      const rationale = matches.length
        ? `Subdomain keywords suggest ${matches.join(', ')} — leading indicator for product or vertical launch`
        : (isWildcard ? 'Wildcard cert provisioned — defensive or umbrella coverage' : 'New subdomain provisioned without obvious keyword signal');

      const signal = {
        hashId,
        companyId: company.id,
        sourceKind: 'cert-transparency',
        sourceUrl: `https://crt.sh/?q=${encodeURIComponent(host)}`,
        title: `New subdomain on ${company.domain}: ${host}`,
        link: `https://${host.replace(/^\*\./, '')}`,
        summary,
        signalType: 'new_subdomain',
        confidence: 0.95,
        rationale,
        companyRelevance: 'direct',
        classifyMethod: 'heuristic',
        impactScore: score,
        impactBand: impactBand(score),
        firstSeen: new Date().toISOString(),
      };

      const emoji = score >= 80 ? '🔥' : score >= 60 ? '📣' : '·';
      console.log(`    ${emoji} [${signal.impactBand}] score=${score} ${host}${matches.length ? `  → ${matches.join(', ')}` : ''}`);

      if (!DRY_RUN) {
        await appendSignal(signal);
        await notifySignal(signal, { companyName: company.name });
      }
      emitted++;
    }
    if (added.length > emitted + skippedDup) {
      console.log(`    (capped at ${MAX_NEW_SIGNALS_PER_COMPANY} per company; ${added.length - emitted - skippedDup} additional new subdomains not signalled)`);
    }
    if (skippedDup > 0) {
      console.log(`    (${skippedDup} already-emitted subdomains skipped)`);
    }
  }

  if (!DRY_RUN) {
    await saveCertSnapshot(company.id, {
      subdomains: currentList,
      lastCheck: new Date().toISOString(),
    });
  }
  return { newCount: firstRun ? 0 : added.length, skippedCount: 0 };
}

// ─── utils ─────────────────────────────────────────────────────────────────
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

main().catch((err) => {
  console.error('[cert-watch] fatal:', err);
  process.exit(1);
});
