// core/artifacts.mjs — the ONE safe way to read and write a generated document.
//
// THE HAZARD THIS EXISTS TO PREVENT
//
// Battlecards carry two kinds of content in one file: an AUTO section regenerated by an
// LLM, and a HUMAN section holding the most valuable material in the system — kill shots
// a rep wrote after a real call. `/api/capture` used to append straight to disk.
//
// So the obvious migration — "make the database canonical, sync it to disk" — would have
// silently destroyed every captured kill shot the first time the cron regenerated a card,
// because the database had never seen them. The 10-20 minute battlecard refresh is also a
// race against any capture happening during it.
//
// The rule that makes this safe, and the reason every writer must come through here:
//
//   EVERY WRITER READ-MODIFY-WRITES THE STORED RECORD AND MIRRORS TO DISK.
//   NOBODY WRITES THE FILE DIRECTLY.
//
// Reads prefer the database and fall back to disk, so a deployment that has not migrated
// yet keeps working, and a fresh clone with files but no rows still renders.

import fs from 'node:fs';
import path from 'node:path';
import { loadArtifact, saveArtifact, listArtifacts, deleteArtifact } from './store.mjs';
import { BATTLECARDS_DIR, BRIEFS_DIR, TALK_TRACKS_DIR, TRANSCRIPTS_DIR, ensureDir } from '../runtime/paths.mjs';

export const AUTO_START = '<!-- AUTO:START -->';
export const AUTO_END = '<!-- AUTO:END -->';

/**
 * Where each artifact kind mirrors to on disk.
 *
 * `transcript` keys are `<companyId>/<videoId>`, which is why its mirror lands at the
 * same `data/transcripts/<companyId>/<videoId>.json` path the archive has always used —
 * adoption does not move or rewrite a single existing file.
 */
const MIRROR = {
  battlecard: (key) => path.join(BATTLECARDS_DIR, `${key}.md`),
  brief: (key) => path.join(BRIEFS_DIR, `${key}.md`),
  talktrack: (key) => path.join(TALK_TRACKS_DIR, `${key}.json`),
  transcript: (key) => path.join(TRANSCRIPTS_DIR, `${key}.json`),
};

/** Base directory each kind mirrors under, for disk sweeps. */
const KIND_ROOT = {
  battlecard: BATTLECARDS_DIR,
  brief: BRIEFS_DIR,
  talktrack: TALK_TRACKS_DIR,
  transcript: TRANSCRIPTS_DIR,
};

function mirrorPath(kind, artifactKey) {
  const fn = MIRROR[kind];
  return fn ? fn(artifactKey) : null;
}

/**
 * Read an artifact body. Database first, disk as fallback.
 * @returns {Promise<{body:string, source:'db'|'disk'|null, metadata:object|null}>}
 */
export async function readArtifact(kind, artifactKey) {
  try {
    const row = await loadArtifact(kind, artifactKey);
    if (row?.body) return { body: row.body, source: 'db', metadata: row.metadata ?? null };
  } catch { /* fall through to disk — a missing table must not break a read */ }

  const file = mirrorPath(kind, artifactKey);
  if (file && fs.existsSync(file)) {
    return { body: fs.readFileSync(file, 'utf8'), source: 'disk', metadata: null };
  }
  return { body: '', source: null, metadata: null };
}

/**
 * Write an artifact: database first, then mirror to disk.
 *
 * The disk write happens only after the database write succeeds, so the two can never
 * disagree in the direction that loses data — a file newer than the row would be
 * overwritten by the next regeneration.
 */
export async function writeArtifact({ kind, artifactKey, companyId = null, scope = null, body, metadata = null }) {
  await saveArtifact({ kind, artifactKey, companyId, scope, body, metadata });
  const file = mirrorPath(kind, artifactKey);
  if (file) {
    ensureDir(path.dirname(file));
    fs.writeFileSync(file, body, 'utf8');
  }
  return { kind, artifactKey, mirrored: !!file };
}

/**
 * Read-modify-write. `mutate(currentBody)` returns the new body.
 *
 * This is the only safe mutation for anything with a HUMAN section: it re-reads
 * immediately before writing, so a capture that landed while an LLM was generating for
 * 10+ minutes is preserved rather than clobbered by a stale in-memory copy.
 */
export async function updateArtifact({ kind, artifactKey, companyId = null, scope = null, metadata = null }, mutate) {
  const { body: current } = await readArtifact(kind, artifactKey);
  const next = await mutate(current || '');
  if (typeof next !== 'string') throw new Error('updateArtifact: mutate must return a string body');
  return writeArtifact({ kind, artifactKey, companyId, scope, body: next, metadata });
}

// ── JSON artifacts ──────────────────────────────────────────────────────────
// Talk tracks and similar structured records. Same canonical-database, mirror-to-disk
// contract as the markdown documents; the only difference is the body is serialised JSON.

/** Read a JSON artifact. Returns null when absent or unparseable. */
export async function readJsonArtifact(kind, artifactKey) {
  const { body } = await readArtifact(kind, artifactKey);
  if (!body) return null;
  try { return JSON.parse(body); } catch { return null; }
}

/** Write a JSON artifact — database first, then the disk mirror. */
export async function writeJsonArtifact({ kind, artifactKey, companyId = null, scope = null, value, metadata = null }) {
  return writeArtifact({
    kind, artifactKey, companyId, scope, metadata,
    body: JSON.stringify(value, null, 2),
  });
}

/**
 * Every artifact of a kind, database first with a disk sweep merged in.
 *
 * The disk sweep is what keeps records written before adoption visible — dropping them
 * silently would be the same failure this whole layer exists to prevent, just quieter.
 */
export async function listJsonArtifacts(kind, { companyId = null } = {}) {
  const byKey = new Map();

  try {
    for (const row of await listArtifacts({ kind, companyId })) {
      const value = await readJsonArtifact(kind, row.artifactKey);
      if (value) byKey.set(row.artifactKey, { ...value, _key: row.artifactKey, _source: 'db' });
    }
  } catch { /* table missing or unreachable — the disk sweep still answers */ }

  const root = KIND_ROOT[kind];
  if (root) {
    for (const key of sweepDisk(kind, root, companyId)) {
      if (byKey.has(key)) continue;
      const value = await readJsonArtifact(kind, key);
      if (value) byKey.set(key, { ...value, _key: key, _source: 'disk' });
    }
  }

  return [...byKey.values()];
}

/** Enumerate `<root>/<companyId>/<slug>.json` mirrors as artifact keys. */
function sweepDisk(kind, root, companyId) {
  const keys = [];
  if (!fs.existsSync(root)) return keys;
  const dirs = companyId ? [companyId] : fs.readdirSync(root);
  for (const dir of dirs) {
    const full = path.join(root, dir);
    let stat;
    try { stat = fs.statSync(full); } catch { continue; }
    if (!stat.isDirectory()) continue;
    for (const f of fs.readdirSync(full)) {
      if (f.endsWith('.json')) keys.push(`${dir}/${f.slice(0, -5)}`);
    }
  }
  return keys;
}

/** Delete an artifact and its disk mirror. Idempotent. */
export async function removeArtifact(kind, artifactKey) {
  let deleted = 0;
  try { ({ deleted } = await deleteArtifact(kind, artifactKey)); } catch { /* table may not exist */ }
  const file = mirrorPath(kind, artifactKey);
  if (file && fs.existsSync(file)) { fs.rmSync(file, { force: true }); deleted = Math.max(deleted, 1); }
  return { deleted };
}

/**
 * Replace ONLY the AUTO section, leaving everything a human wrote untouched.
 * Returns null when the markers are absent or malformed, so callers can tell
 * "nothing to splice" from "spliced an empty section".
 */
export function spliceAutoSection(existing, newAuto) {
  if (!existing) return null;
  const s = existing.indexOf(AUTO_START);
  const e = existing.indexOf(AUTO_END);
  if (s === -1 || e === -1 || e < s) return null;
  return existing.slice(0, s) + AUTO_START + '\n' + newAuto + '\n' + existing.slice(e);
}

/**
 * Regenerate the AUTO half of a document while preserving the HUMAN half.
 * If the document does not exist yet, `renderFull` builds it from scratch.
 */
export async function updateAutoSection({ kind, artifactKey, companyId = null, scope = null, metadata = null },
  { autoBody, renderFull }) {
  return updateArtifact({ kind, artifactKey, companyId, scope, metadata }, (current) => {
    const spliced = spliceAutoSection(current, autoBody);
    if (spliced) return spliced;
    if (typeof renderFull === 'function') return renderFull(autoBody);
    return `${AUTO_START}\n${autoBody}\n${AUTO_END}\n`;
  });
}
