import { STORAGE, IMPACT_COLORS, SIGNAL_TYPES, impactBand, timeAgo } from './shared/constants.js';
import { apiFetch, getApiUrl } from './shared/api.js';
import { aiStatus, summarizeText, classifySignal, rewriteNotes, intelCheck } from './shared/ai.js';

// ─── State ───
let state = {
  companies: [],
  signals: [],
  filtered: [],
  clipData: null,
  intelData: null,  // pre-baked company intel from data/companies.json
  ai: { summarizer: 'unavailable', prompt: 'unavailable', rewriter: 'unavailable' },
};

// ─── DOM refs ───
const $errorBanner = document.getElementById('error-banner');

// ─── Tab switching ───
document.querySelectorAll('.tab').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById(`tab-${btn.dataset.tab}`).classList.add('active');
    // Hide signal detail when switching tabs
    document.getElementById('signal-detail').classList.add('hidden');
  });
});

// ─── Init ───
async function init() {
  chrome.action.setBadgeText({ text: '' });

  const apiUrl = await getApiUrl();
  if (!apiUrl) {
    showSetupScreen();
    return;
  }

  state.ai = await aiStatus();
  setupAiButtons();

  // Check for pending clip data — auto-switch to Intel tab
  const clipStore = await chrome.storage.local.get(STORAGE.pendingClip);
  state.clipData = clipStore[STORAGE.pendingClip] || null;

  if (state.clipData) {
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    document.querySelector('[data-tab="intel"]').classList.add('active');
    document.getElementById('tab-intel').classList.add('active');
  }

  try {
    const [configRes, signalsData, cronRes] = await Promise.all([
      apiFetch('/api/config'),
      apiFetch('/api/signals'),
      apiFetch('/api/cron-status').catch(() => null),
    ]);

    state.companies = configRes.companies || [];
    state.signals = Array.isArray(signalsData) ? signalsData : (signalsData.signals || []);
    state.filtered = state.signals;

    // Load pre-baked intel data (generated by `npm run chrome-data`)
    try {
      const intelRes = await fetch(chrome.runtime.getURL('data/companies.json'));
      if (intelRes.ok) state.intelData = await intelRes.json();
    } catch { /* no local data yet — Intel Check falls back to API signals */ }

    renderDashboard(cronRes);
    populateFilters();
    populateIntelTab();
    loadSettings();
  } catch (err) {
    showError(err.message);
  }
}

function showSetupScreen() {
  document.querySelector('.tabs').style.display = 'none';
  document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));

  const $dashboard = document.getElementById('tab-dashboard');
  $dashboard.classList.add('active');
  $dashboard.innerHTML = `
    <div class="setup-screen">
      <div class="setup-icon">◆</div>
      <h2>Welcome to Signal</h2>
      <p>Connect your dashboard to get started.</p>
      <button id="btn-open-settings-setup" class="primary-btn">Open Settings</button>
      <p class="setup-hint">Enter your Signal dashboard URL<br>(e.g. https://your-app.up.railway.app)</p>
    </div>
  `;
  document.getElementById('btn-open-settings-setup').addEventListener('click', () => {
    document.querySelector('.tabs').style.display = 'flex';
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    document.querySelector('[data-tab="settings"]').classList.add('active');
    document.getElementById('tab-settings').classList.add('active');
  });
}

function showError(msg) {
  $errorBanner.textContent = msg;
  $errorBanner.className = 'banner err';
}

// ─── Dashboard ───
function renderDashboard(cronRes) {
  const all = state.filtered;
  const critical = all.filter(s => s.impactBand === 'critical' || s.signalType === 'convergence');

  document.getElementById('stat-total').textContent = all.length;
  document.getElementById('stat-critical').textContent = critical.length;

  if (cronRes && cronRes.lastRun) {
    document.getElementById('stat-cron').textContent = timeAgo(cronRes.lastRun);
  } else {
    document.getElementById('stat-cron').textContent = '—';
  }

  const $list = document.getElementById('signal-list');
  const $heading = document.getElementById('signal-heading');
  const top = all.slice(0, 50);

  $heading.textContent = state.filtered.length < state.signals.length
    ? `Filtered signals (${state.filtered.length})`
    : 'Recent signals';

  if (top.length === 0) {
    $list.innerHTML = '<div class="loading">No signals match</div>';
    return;
  }

  $list.innerHTML = top.map((s, i) => {
    const band = s.impactBand || 'noise';
    const color = IMPACT_COLORS[band] || IMPACT_COLORS.noise;
    const company = state.companies.find(c => c.id === s.companyId);
    const companyName = company?.name || s.companyId;
    const summary = s.summary || '';
    return `
      <div class="signal-row" data-idx="${i}" style="--band-color: ${color}">
        <div class="signal-info">
          <div class="signal-title">${esc(s.title || summary.slice(0, 100) || '—')}</div>
          <div class="signal-meta">
            <span class="company">${esc(companyName)}</span> · ${esc(s.signalType || '')} · ${timeAgo(s.firstSeen)}
          </div>
          ${summary ? `<div class="signal-summary">${esc(summary)}</div>` : ''}
          <div class="tldr-slot" data-summary="${esc(summary)}"></div>
        </div>
        <span class="signal-badge band-${band}">${s.impactScore || '?'}</span>
        ${state.ai.summarizer !== 'unavailable' ? '<button class="btn-tldr" title="AI TL;DR">✨</button>' : ''}
      </div>`;
  }).join('');

  // Click → open signal detail
  $list.querySelectorAll('.signal-row').forEach(row => {
    row.addEventListener('click', (e) => {
      if (e.target.classList.contains('btn-tldr')) return;
      const idx = Number(row.dataset.idx);
      showSignalDetail(state.filtered[idx]);
    });
  });

  // TL;DR buttons
  $list.querySelectorAll('.btn-tldr').forEach(btn => {
    btn.addEventListener('click', async (e) => {
      e.stopPropagation();
      const row = btn.closest('.signal-row');
      const slot = row.querySelector('.tldr-slot');
      const summary = slot.dataset.summary;
      if (!summary || slot.querySelector('.tldr-result')) return;
      btn.textContent = '⏳';
      const result = await summarizeText(summary);
      if (result) {
        slot.innerHTML = `<div class="tldr-result">${esc(result)}</div>`;
      }
      btn.textContent = '✨';
    });
  });
}

// ─── Signal detail view ───
function showSignalDetail(signal) {
  const $detail = document.getElementById('signal-detail');
  const $content = document.getElementById('detail-content');
  const company = state.companies.find(c => c.id === signal.companyId);
  const companyName = company?.name || signal.companyId;
  const band = signal.impactBand || 'noise';
  const color = IMPACT_COLORS[band] || IMPACT_COLORS.noise;

  $content.innerHTML = `
    <div class="detail-header">
      <div class="detail-title">${esc(signal.title || signal.summary?.slice(0, 120) || '—')}</div>
      <div class="detail-meta">
        <span class="tag band-${band}">${(band).toUpperCase()} ${signal.impactScore || '?'}</span>
        <span>${esc(companyName)}</span>
        <span>${esc(signal.signalType || '')}</span>
        <span>${timeAgo(signal.firstSeen)}</span>
      </div>
    </div>

    ${signal.summary ? `
    <div class="detail-section">
      <h4>Summary</h4>
      <p>${esc(signal.summary)}</p>
    </div>` : ''}

    ${signal.soWhat ? `
    <div class="detail-section">
      <h4>So What</h4>
      <p>${esc(signal.soWhat)}</p>
    </div>` : ''}

    ${signal.counterSignal ? `
    <div class="detail-section">
      <h4>Counter-Signal</h4>
      <p>${esc(signal.counterSignal)}</p>
    </div>` : ''}

    ${signal.link ? `
    <div class="detail-section">
      <h4>Source</h4>
      <p><a href="${esc(signal.link)}" id="detail-link">${esc(signal.link)}</a></p>
    </div>` : ''}

    ${signal.hashId ? `
    <div class="detail-section">
      <h4>Hash ID</h4>
      <p style="font-family: monospace; font-size: 11px; color: #6b7484;">${esc(signal.hashId)}</p>
    </div>` : ''}

    <div class="detail-section">
      <h4>Raw data</h4>
      <details>
        <summary style="cursor:pointer; color:#6b7484; font-size:11px;">Show JSON</summary>
        <pre style="margin-top:8px; padding:10px; background:#13171f; border-radius:6px; font-size:11px; overflow-x:auto; color:#a8b3c2; line-height:1.4;">${esc(JSON.stringify(signal, null, 2))}</pre>
      </details>
    </div>
  `;

  // Link click → open in new tab
  const $link = $content.querySelector('#detail-link');
  if ($link) {
    $link.addEventListener('click', (e) => {
      e.preventDefault();
      chrome.tabs.create({ url: $link.href });
    });
  }

  $detail.classList.remove('hidden');
}

document.getElementById('detail-back').addEventListener('click', () => {
  document.getElementById('signal-detail').classList.add('hidden');
});

// ─── Filters ───
function populateFilters() {
  const $company = document.getElementById('filter-company');
  state.companies.forEach(c => {
    const opt = document.createElement('option');
    opt.value = c.id;
    opt.textContent = c.name || c.id;
    $company.appendChild(opt);
  });

  const $type = document.getElementById('filter-type');
  // Collect actual types from signals
  const usedTypes = [...new Set(state.signals.map(s => s.signalType).filter(Boolean))];
  usedTypes.sort();
  usedTypes.forEach(t => {
    const opt = document.createElement('option');
    opt.value = t;
    opt.textContent = t.replace(/_/g, ' ');
    $type.appendChild(opt);
  });

  // Listen for filter changes
  $company.addEventListener('change', applyFilters);
  document.getElementById('filter-band').addEventListener('change', applyFilters);
  $type.addEventListener('change', applyFilters);
}

function applyFilters() {
  const companyVal = document.getElementById('filter-company').value;
  const bandVal = document.getElementById('filter-band').value;
  const typeVal = document.getElementById('filter-type').value;

  state.filtered = state.signals.filter(s => {
    if (companyVal && s.companyId !== companyVal) return false;
    if (bandVal && (s.impactBand || 'noise') !== bandVal) return false;
    if (typeVal && s.signalType !== typeVal) return false;
    return true;
  });

  renderDashboard(null);
}

// ─── Intel tab (unified Check → Clip flow) ───
function populateIntelTab() {
  const $company = document.getElementById('intel-company');
  while ($company.options.length > 1) $company.options.remove(1);

  state.companies.filter(c => !c.isUs).forEach(c => {
    const opt = document.createElement('option');
    opt.value = c.id;
    opt.textContent = c.name || c.id;
    $company.appendChild(opt);
  });

  // Populate signal type dropdown for clip form
  const $type = document.getElementById('intel-clip-type');
  SIGNAL_TYPES.forEach(t => {
    const opt = document.createElement('option');
    opt.value = t;
    opt.textContent = t.replace(/_/g, ' ');
    $type.appendChild(opt);
  });

  // Auto-fill page info from current tab
  chrome.tabs.query({ active: true, currentWindow: true }).then(([tab]) => {
    if (tab) {
      document.getElementById('intel-page-title').textContent = tab.title || '—';
      document.getElementById('intel-page-url').textContent = tab.url || '—';
      document.getElementById('intel-clip-link').value = tab.url || '';
      state.currentTab = tab;
    }
  });

  // Enable check button when company selected
  $company.addEventListener('change', () => {
    document.getElementById('btn-intel-check').disabled = !$company.value;
  });

  // If pending clip data, auto-select company + run check
  if (state.clipData) {
    autoFillFromClipData();
  }
}

async function autoFillFromClipData() {
  if (state.ai.prompt === 'unavailable' || !state.clipData) return;

  const textToClassify = state.clipData.pageText || state.clipData.selectedText || state.clipData.title || '';
  if (!textToClassify) return;

  try {
    const result = await classifySignal(textToClassify, state.companies, SIGNAL_TYPES);
    if (result && result.companyId !== 'unknown') {
      document.getElementById('intel-company').value = result.companyId;
      document.getElementById('btn-intel-check').disabled = false;
      // Auto-trigger the check
      document.getElementById('btn-intel-check').click();
    }
  } catch {}
}

// ─── AI buttons ───
function setupAiButtons() {
  if (state.ai.summarizer !== 'unavailable') {
    document.getElementById('btn-summarize-page').classList.remove('hidden');
  }
  if (state.ai.rewriter !== 'unavailable') {
    document.getElementById('btn-rewrite').classList.remove('hidden');
  }
}

// Summarize page → fill notes
document.getElementById('btn-summarize-page').addEventListener('click', async () => {
  const btn = document.getElementById('btn-summarize-page');
  btn.textContent = '⏳ Summarizing…';
  btn.disabled = true;

  try {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (!tab) return;

    const response = await chrome.tabs.sendMessage(tab.id, { type: 'GET_PAGE_TEXT' });
    if (response?.pageText) {
      const summary = await summarizeText(response.pageText);
      if (summary) {
        document.getElementById('intel-clip-notes').value = summary;
      }
    }
  } catch {}
  finally {
    btn.textContent = '✨ Summarize';
    btn.disabled = false;
  }
});

// Rewrite notes
document.getElementById('btn-rewrite').addEventListener('click', async () => {
  const $notes = document.getElementById('intel-clip-notes');
  const text = $notes.value.trim();
  if (!text) return;

  const btn = document.getElementById('btn-rewrite');
  btn.textContent = '⏳';
  btn.disabled = true;

  try {
    const result = await rewriteNotes(text);
    if (result) $notes.value = result;
  } catch {}

  btn.textContent = '✨ Rewrite';
  btn.disabled = false;
});

// ─── Intel Check (Step 1) ───
document.getElementById('btn-intel-check').addEventListener('click', async () => {
  const companyId = document.getElementById('intel-company').value;
  if (!companyId) return;

  const $btn = document.getElementById('btn-intel-check');
  const $status = document.getElementById('intel-check-status');
  const $result = document.getElementById('intel-result');
  const $clipSection = document.getElementById('intel-step-clip');

  $btn.disabled = true;
  $btn.textContent = '⏳ Analyzing…';
  $status.textContent = '';
  $result.classList.add('hidden');
  $clipSection.classList.add('hidden');

  try {
    // 1. Get page text from content script
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (!tab) throw new Error('No active tab');

    let pageText = '';
    try {
      const response = await chrome.tabs.sendMessage(tab.id, { type: 'GET_PAGE_TEXT' });
      pageText = response?.pageText || '';
    } catch {
      pageText = tab.title || '';
    }

    if (!pageText || pageText.length < 20) {
      $status.textContent = 'Not enough page content to analyze';
      $status.style.color = '#ff9a4d';
      return;
    }

    // 2. Get company intel — prefer local pre-baked data, fall back to API signals
    const company = state.companies.find(c => c.id === companyId);
    const companyName = company?.name || companyId;
    const localIntel = state.intelData?.companies?.[companyId];
    let signalsOrDigest;
    let signalCount;

    if (localIntel?.digest?.length) {
      signalsOrDigest = localIntel.digest;
      signalCount = localIntel.signalCount;
      const age = state.intelData.generated
        ? Math.round((Date.now() - new Date(state.intelData.generated).getTime()) / 86400_000)
        : '?';
      $status.textContent = `Comparing against ${signalCount} signals for ${companyName} (local snapshot, ${age}d old)…`;
    } else {
      signalsOrDigest = state.signals.filter(s => s.companyId === companyId);
      signalCount = signalsOrDigest.length;
      $status.textContent = `Comparing against ${signalCount} signals for ${companyName} (live API)…`;
    }
    $status.style.color = '#6b7484';

    // 3. Run AI comparison
    const analysis = await intelCheck(pageText, companyName, signalsOrDigest);

    if (!analysis) {
      $status.textContent = 'Prompt API unavailable — enable Chrome AI flags';
      $status.style.color = '#ff5a5a';
      return;
    }

    // 4. Show analysis result
    $status.textContent = '';
    $result.classList.remove('hidden');
    document.getElementById('intel-analysis').textContent = analysis;

    // 5. Show clip form (pre-filled)
    $clipSection.classList.remove('hidden');
    document.getElementById('intel-clip-title').value = tab.title || '';

    // Try to auto-detect signal type
    if (state.ai.prompt !== 'unavailable') {
      try {
        const classification = await classifySignal(pageText, state.companies, SIGNAL_TYPES);
        if (classification && classification.signalType) {
          document.getElementById('intel-clip-type').value = classification.signalType;
          const $banner = document.getElementById('intel-ai-banner');
          const $bannerText = document.getElementById('intel-ai-text');
          $banner.classList.remove('hidden');
          $bannerText.textContent = `🤖 Detected: ${classification.signalType} (${classification.confidence}%)`;
        }
      } catch {}
    }

    // Pre-fill notes with a condensed version of the analysis
    if (state.ai.summarizer !== 'unavailable') {
      const summary = await summarizeText(pageText);
      if (summary) document.getElementById('intel-clip-notes').value = summary;
    }

  } catch (err) {
    $status.textContent = `❌ ${err.message}`;
    $status.style.color = '#ff5a5a';
  } finally {
    $btn.disabled = !document.getElementById('intel-company').value;
    $btn.textContent = 'Check page against intel';
  }
});

// Re-check button
document.getElementById('btn-intel-recheck').addEventListener('click', () => {
  document.getElementById('btn-intel-check').click();
});

// ─── Submit clip to Turso (Step 2) ───
document.getElementById('btn-submit-clip').addEventListener('click', async () => {
  const $btn = document.getElementById('btn-submit-clip');
  const $status = document.getElementById('intel-clip-status');

  const companyId = document.getElementById('intel-company').value;

  const payload = {
    competitorId: companyId,
    signalType: document.getElementById('intel-clip-type').value || 'other',
    title: document.getElementById('intel-clip-title').value,
    notes: document.getElementById('intel-clip-notes').value,
    link: document.getElementById('intel-clip-link').value,
  };

  if (!payload.competitorId) {
    $status.textContent = 'Company required — select above';
    $status.style.color = '#ff5a5a';
    return;
  }
  if (!payload.title) {
    $status.textContent = 'Title required';
    $status.style.color = '#ff5a5a';
    return;
  }

  $btn.disabled = true;
  $btn.textContent = 'Saving…';

  try {
    await apiFetch('/api/clip', { method: 'POST', body: JSON.stringify(payload) });
    $status.textContent = '✅ Signal saved to Turso!';
    $status.style.color = '#45c66a';
    await chrome.storage.local.remove(STORAGE.pendingClip);
    setTimeout(() => {
      document.getElementById('intel-clip-title').value = '';
      document.getElementById('intel-clip-notes').value = '';
      document.getElementById('intel-clip-type').value = '';
      document.getElementById('intel-clip-link').value = '';
      $status.textContent = '';
      $btn.disabled = false;
      $btn.textContent = 'Save signal to Turso';
    }, 1500);
  } catch (err) {
    $status.textContent = `❌ ${err.message}`;
    $status.style.color = '#ff5a5a';
    $btn.disabled = false;
    $btn.textContent = 'Save signal to Turso';
  }
});

// ─── Settings ───
function loadSettings() {
  chrome.storage.sync.get([STORAGE.apiUrl, STORAGE.pollMin, STORAGE.notifThreshold], (data) => {
    document.getElementById('api-url').value = data[STORAGE.apiUrl] || '';
    document.getElementById('poll-min').value = data[STORAGE.pollMin] || 5;
    document.getElementById('notif-threshold').value = String(data[STORAGE.notifThreshold] ?? 80);
  });

  // AI status display
  const $aiStatus = document.getElementById('ai-status');
  const row = (label, val) => {
    const cls = val && val !== 'unavailable' ? 'ai-available' : 'ai-unavailable';
    const text = val && val !== 'unavailable' ? '✓ ' + val : '✗ unavailable';
    return `<div class="ai-row"><span>${label}</span><span class="${cls}">${text}</span></div>`;
  };
  $aiStatus.innerHTML =
    row('Summarizer', state.ai.summarizer) +
    row('Prompt API', state.ai.prompt) +
    row('Rewriter', state.ai.rewriter);
}

document.getElementById('save-btn').addEventListener('click', async () => {
  const apiUrl = document.getElementById('api-url').value.trim().replace(/\/$/, '');
  const pollMin = Math.max(1, Math.min(60, Number(document.getElementById('poll-min').value) || 5));
  const threshold = Number(document.getElementById('notif-threshold').value);
  const $status = document.getElementById('settings-status');

  await chrome.storage.sync.set({
    [STORAGE.apiUrl]: apiUrl,
    [STORAGE.pollMin]: pollMin,
    [STORAGE.notifThreshold]: threshold,
  });

  await chrome.alarms.clear('signal-poll');
  await chrome.alarms.create('signal-poll', { periodInMinutes: pollMin });

  $status.textContent = 'Saved ✓';
  setTimeout(() => { $status.textContent = ''; }, 2000);
});

document.getElementById('test-btn').addEventListener('click', async () => {
  const apiUrl = document.getElementById('api-url').value.trim().replace(/\/$/, '');
  const $status = document.getElementById('settings-status');
  if (!apiUrl) { $status.textContent = '❌ Enter an API URL first'; return; }
  await chrome.storage.sync.set({ [STORAGE.apiUrl]: apiUrl });
  try {
    const res = await apiFetch('/api/config');
    const count = res.companies?.length || 0;
    $status.textContent = `✅ Connected — ${count} companies tracked`;
  } catch (err) {
    $status.textContent = `❌ ${err.message}`;
  }
});

// ─── Header actions ───
document.getElementById('btn-refresh').addEventListener('click', () => init());
document.getElementById('btn-settings').addEventListener('click', () => {
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
  document.querySelector('[data-tab="settings"]').classList.add('active');
  document.getElementById('tab-settings').classList.add('active');
});
document.getElementById('btn-open-dashboard').addEventListener('click', async () => {
  const apiUrl = await getApiUrl();
  if (apiUrl) chrome.tabs.create({ url: apiUrl });
});

// ─── Util ───
function esc(s) {
  const d = document.createElement('div');
  d.textContent = s;
  return d.innerHTML;
}

init();
