// config/companies.default.mjs — the SHIPPED DEMO roster.
//
// ┌─────────────────────────────────────────────────────────────────────────┐
// │ To track your own market, DO NOT edit this file.                        │
// │ Copy it to `config/companies.local.mjs` and edit that. It is gitignored │
// │ and overrides this one, so you can pull upstream forever without ever   │
// │ hitting a merge conflict in the file you customised.                    │
// └─────────────────────────────────────────────────────────────────────────┘
//
// This is the ONLY place brand names are allowed to appear. `npm run smoke` fails the
// build if one leaks into a watcher, prompt or classifier.
//
// The demo watches AI coding agents and prompt-to-app builders, in market-watch mode:
// no entry carries `isUs`, so there is no home team and the analysis is neutral.
//
// CHOOSING AN ANCHOR — three modes, and you pick by setting at most one flag.
//
//   isUs: true    You ARE this vendor. Turns on partisan framing: a self-card, win
//                 themes, "how do we beat them" talk tracks. The classic sales setup.
//
//   isMain: true  This company is the SUBJECT, but you are not it. An analyst tracking
//                 the category leader, an investor watching a holding, a team evaluating
//                 a tool they do not sell. Comparison anchors here; the language stays
//                 neutral — no "we", no win themes, no self-card.
//
//   neither       Pure market-watch. Every company is peer to every other, and the
//                 dashboard compares any two.
//
// Nothing breaks in any of them. Before `isMain` existed, a deployment without `isUs`
// left the Battle view with no anchor and it rendered permanently empty — the most
// useful comparison in a market-watch setup was the one you could not have.
//
// FIELD NOTES
//   query       REQUIRED and must be QUALIFIED. Several names here are ordinary English
//               or code tokens, so an unqualified query returns mostly junk. Blocking a
//               collision at the feed level is the cheapest place to do it.
//   repos       VERIFY before adding — every entry becomes a releases.atom fetch, and a
//               guessed path is a 404 on the user's first run. Leave empty for
//               closed-source products rather than guessing.
//   subreddits  Higher signal-to-noise than site-wide search, but Reddit rate-limits
//               unauthenticated access hard; treat these as best-effort.
//   sidebarNote OPTIONAL short badge shown beside the company in the dashboard sidebar
//               ("employer", "incumbent", "partner"). Keep it to one word — it renders
//               as a pill. Omit unless it genuinely helps you read the list.
//   changelog   Informational for now. Several vendors render changelogs as client-side
//               HTML with no RSS, which needs an HTML-diff watcher, not a feed.

export const companies = {
  // ───────── pro-dev: sold to professional engineers ─────────
  // Evaluated on repo-wide context, terminal execution, git-native diffs, model choice,
  // self-hosting and compliance.
  claudecode: {
    id: 'claudecode', name: 'Claude Code', domain: 'claude.com',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['Claude Code', 'claude-code'],
    query: '"Claude Code" OR "claude-code"',
    collidesWith: 'the given name Claude (Monet, Debussy) and anyone called Claude',
    repos: ['anthropics/claude-code'],
    subreddits: ['ClaudeAI', 'ClaudeCode'],
    segments: ['dev', 'enterprise'], personas: ['engineer', 'engineering-manager'],
    positioningHypothesis: 'Terminal-native agentic coding — long-horizon tasks, MCP and subagents',
  },
  cursor: {
    id: 'cursor', name: 'Cursor', domain: 'cursor.com',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['Cursor AI', 'cursor.com', 'cursor.sh', 'Anysphere'],
    query: '"Cursor AI" OR "cursor.com" OR "Anysphere"',
    collidesWith: 'a mouse cursor, a database cursor, the CSS property',
    matchCapitalizedBare: true,   // "use Cursor" is the product; "the cursor" is not
    repos: ['cursor/cursor'],   // verified 200; getcursor/cursor 301-redirects here
    subreddits: ['cursor'],
    segments: ['dev', 'enterprise'], personas: ['engineer', 'engineering-manager'],
    positioningHypothesis: 'AI-native fork of VS Code — inline edits plus repo-wide agent, developer-led adoption',
  },
  codex: {
    id: 'codex', name: 'OpenAI Codex', domain: 'openai.com',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['OpenAI Codex', 'Codex CLI', 'codex-cli'],
    query: '"OpenAI Codex" OR "Codex CLI"',
    collidesWith: 'Codex Alimentarius, medieval manuscripts, Warhammer codices',
    repos: ['openai/codex'],
    subreddits: ['OpenAI'],
    segments: ['dev', 'enterprise'], personas: ['engineer', 'engineering-manager'],
    positioningHypothesis: 'Agentic coding surface from OpenAI — cloud + CLI, tied to the OpenAI model line',
  },
  windsurf: {
    id: 'windsurf', name: 'Windsurf', domain: 'windsurf.com',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['Windsurf Editor', 'Windsurf IDE', 'windsurf.com', 'Codeium'],
    query: '"Windsurf Editor" OR "Windsurf IDE" OR "Codeium Windsurf"',
    collidesWith: 'the watersport',
    matchCapitalizedBare: true,   // "Windsurf" the product; "windsurfing" is a different token anyway
    repos: [],
    subreddits: ['windsurf', 'Codeium'],
    segments: ['dev', 'enterprise'], personas: ['engineer'],
    positioningHypothesis: 'Agentic IDE from the Codeium lineage — enterprise self-host story',
  },

  // Added 2026-08-02 from answer-engine visibility data (see docs/decisions/roster.md).
  // These were named by AI answer engines on buying-intent questions far more often than
  // some brands already tracked — Copilot alone took 20% share of voice while being
  // entirely absent from this roster.
  copilot: {
    id: 'copilot', name: 'GitHub Copilot', domain: 'github.com',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['GitHub Copilot', 'Copilot Workspace'],
    // NEVER a bare `Copilot` — Microsoft applies that name to a dozen unrelated products.
    query: '"GitHub Copilot" OR "Copilot Workspace"',
    collidesWith: 'Microsoft 365 Copilot, Copilot Studio, Security Copilot and every other Copilot-branded product',
    matchCapitalizedBare: true,   // qualified forms still preferred; bare Copilot in a coding answer means this one
    repos: ['microsoft/vscode-copilot-release'],   // verified 200
    subreddits: ['GithubCopilot'],
    segments: ['dev', 'enterprise'], personas: ['engineer', 'engineering-manager'],
    positioningHypothesis: 'The incumbent — distribution through GitHub and the enterprise agreements that come with it',
  },
  aider: {
    id: 'aider', name: 'Aider', domain: 'aider.chat',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['Aider AI', 'aider.chat'],
    query: '"Aider AI" OR "aider.chat"',
    collidesWith: 'the ordinary word "aid"/"aider" in French and in accessibility writing',
    matchCapitalizedBare: true,
    repos: ['Aider-AI/aider'],                     // verified 200
    subreddits: ['ChatGPTCoding'],
    segments: ['dev'], personas: ['engineer'],
    positioningHypothesis: 'Open-source terminal pair programmer — git-native, model-agnostic, no vendor lock-in',
  },
  cody: {
    id: 'cody', name: 'Sourcegraph Cody', domain: 'sourcegraph.com',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['Sourcegraph Cody'],
    // Never a bare `Cody` — it is a given name and a place name.
    query: '"Sourcegraph Cody" OR "Cody AI"',
    collidesWith: 'the given name Cody, and Cody, Wyoming',
    repos: ['sourcegraph/cody-public-snapshot'],   // verified 200; sourcegraph/cody is 404
    subreddits: [],
    segments: ['dev', 'enterprise'], personas: ['engineer', 'engineering-manager'],
    positioningHypothesis: 'Code-search lineage — whole-codebase context as the differentiator',
  },
  tabnine: {
    id: 'tabnine', name: 'Tabnine', domain: 'tabnine.com',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['tabnine.com'],
    query: '"Tabnine"',
    collidesWith: '',
    repos: ['codota/TabNine'],                     // verified 200
    subreddits: [],
    segments: ['dev', 'enterprise'], personas: ['engineer'],
    positioningHypothesis: 'Privacy and self-hosting first — the on-prem answer for regulated buyers',
  },
  devin: {
    id: 'devin', name: 'Devin', domain: 'cognition.ai',
    category: 'coding-agent', market: 'pro-dev',
    aliases: ['Devin AI', 'Cognition Devin'],
    query: '"Devin AI" OR "Cognition Devin"',
    collidesWith: 'the given name Devin',
    repos: [],                                     // closed source, no public repo
    subreddits: [],
    segments: ['dev', 'enterprise'], personas: ['engineer', 'engineering-manager'],
    positioningHypothesis: 'Fully autonomous software engineer framing — the most aggressive autonomy claim in the category',
  },

  // ───────── vibe-coding: sold largely to people who are not engineers ─────────
  // Evaluated on instant preview, zero-config hosting, database auto-wiring, credit burn
  // rate, design quality and code exportability. Compliance and CLIs are non-factors.
  lovable: {
    id: 'lovable', name: 'Lovable', domain: 'lovable.dev',
    category: 'app-builder', market: 'vibe-coding',
    aliases: ['lovable.dev', 'Lovable AI', 'GPT Engineer'],
    query: '"lovable.dev" OR "Lovable AI"',
    collidesWith: 'the ordinary English adjective',
    repos: [],
    subreddits: ['lovable'],
    changelog: 'https://lovable.dev/changelog',
    segments: ['smb', 'non-technical'], personas: ['founder', 'product-manager', 'designer'],
    positioningHypothesis: 'Prompt-to-product for non-engineers — design-led output',
  },
  bolt: {
    id: 'bolt', name: 'Bolt', domain: 'bolt.new',
    category: 'app-builder', market: 'vibe-coding',
    aliases: ['bolt.new', 'Bolt.new', 'StackBlitz Bolt'],
    query: '"bolt.new" OR "StackBlitz Bolt"',
    collidesWith: 'Usain Bolt, a fastener, the ride-hailing app, the Disney film',
    repos: ['stackblitz/bolt.new'],
    subreddits: ['Bolt_new'],
    segments: ['dev', 'smb'], personas: ['founder', 'engineer', 'designer'],
    positioningHypothesis: 'In-browser full-stack app generation from a prompt, StackBlitz-backed',
  },
  v0: {
    id: 'v0', name: 'v0', domain: 'v0.dev',
    category: 'app-builder', market: 'vibe-coding',
    aliases: ['v0.dev', 'Vercel v0', 'v0 by Vercel'],
    // NEVER a bare `v0` — it collides with every version string ever written.
    query: '"v0.dev" OR "Vercel v0"',
    collidesWith: 'version strings such as v0.1.2 — almost every bare use',
    repos: [],
    subreddits: ['vercel'],
    changelog: 'https://v0.dev/changelog',
    segments: ['dev', 'smb'], personas: ['engineer', 'designer', 'product-manager'],
    positioningHypothesis: 'Generative UI from Vercel — prompt to React/Tailwind, deploys to Vercel',
  },
  replit: {
    id: 'replit', name: 'Replit', domain: 'replit.com',
    category: 'app-builder', market: 'vibe-coding',
    aliases: ['Replit Agent', 'replit.com'],
    query: '"Replit Agent" OR "replit.com"',
    collidesWith: '',
    repos: [],                  // no public product repo — replit/replit is a 404
    subreddits: ['replit'],
    segments: ['dev', 'smb', 'education'], personas: ['engineer', 'founder', 'student'],
    positioningHypothesis: 'Browser IDE turned agentic app builder — build, host and deploy in one place',
  },
};

// Bare tokens that are ordinary English words or well-known other referents, and so are
// NOT sufficient on their own to attribute an article. Every company still matches via
// its qualified forms, so real coverage is unaffected. Word boundaries do not help here —
// the token matches exactly.
//
// If you change the roster, RE-DERIVE this list. The method is "profile the corpus, see
// which names collide", not this specific set of strings.
export const ambiguousBareTokens = [
  'copilot',   // Microsoft brands a dozen unrelated products Copilot
  'cody',      // a given name, and a town in Wyoming
  'devin',     // a given name
  'aider',     // 'aid'/'aider' in ordinary and French text
  'bolt',      // Usain Bolt · a fastener · the ride-hailing app · the Disney film
  'lovable',   // plain English adjective
  'codex',     // Codex Alimentarius · medieval manuscripts · Warhammer codices
  'claude',    // Claude Monet · Claude Debussy · anyone named Claude
  'cursor',    // mouse cursor · database cursor · CSS `cursor:`
  'windsurf',  // the watersport
  'v0',        // version strings: "v0.1.2", "v0 release" — almost never the Vercel product
  // Deliberately absent: 'replit' — distinctive standalone.
];

/**
 * Names that must NEVER reappear in this codebase.
 *
 * When a deployment is retargeted from one market to another, the old market's brand
 * names have a habit of surviving in prompts, few-shot examples, User-Agent strings and
 * test fixtures long after the roster changed — where they quietly corrupt classification
 * and leak the previous engagement. `npm run smoke` fails if any name listed here appears
 * anywhere outside `config/`.
 *
 * Empty in the shipped demo, on purpose: this repo has nothing to forget. Add your own
 * previous market's names in `config/companies.local.mjs`, which is gitignored.
 */
export const retiredBrands = [];

export default { companies, ambiguousBareTokens, retiredBrands };
